## Importing the Necessary Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import time
import warnings
warnings.filterwarnings('ignore')

# Using seaborn set_style function for better visualizations
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)

## Loading the Data

In [4]:
data = pd.read_csv('kmeans_data/data.csv', header=None)
labels = pd.read_csv('kmeans_data/label.csv', header=None)

In [5]:
data

,0,1,2,3,4,5,6,7,8,9,...,774,775,776,777,778,779,780,781,782,783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
labels

      0
0     7
1     2
2     1
3     0
4     4
...  ..
9995  2
9996  3
9997  4
9998  5
9999  6

[10000 rows x 1 columns]

In [7]:
print(data.shape)
print(labels.shape)

(10000, 784)
(10000, 1)

## Converting the Data and Labels to NumPy Arrays

In [8]:
X = data.values
y = labels.values.flatten()

In [10]:
print(X.dtype)
print(y.dtype)

int64
int64

## Data Exploration

In [11]:
print("Number of samples: ", X.shape[0])
print("Number of features: ", X.shape[1])

Number of samples:  10000
Number of features:  784

In [12]:
print("Unique Classes in Labels: ", np.unique(y))
print("Number of Unique Classes: ", len(np.unique(y)))

Unique Classes in Labels:  [0 1 2 3 4 5 6 7 8 9]
Number of Unique Classes:  10

In [14]:
unique_classes, counts = np.unique(y, return_counts=True)

In [15]:
for label, count in zip(unique_classes, counts):
    perecentage = (count / len(y)) * 100 
    print(f"Class {label}: {count} samples, {perecentage:.2f}% of total")

K = len(unique_classes)
print(f"Total number of clusters (K): {K}")

Class 0: 980 samples, 9.80% of total
Class 1: 1135 samples, 11.35% of total
Class 2: 1032 samples, 10.32% of total
Class 3: 1010 samples, 10.10% of total
Class 4: 982 samples, 9.82% of total
Class 5: 892 samples, 8.92% of total
Class 6: 958 samples, 9.58% of total
Class 7: 1028 samples, 10.28% of total
Class 8: 974 samples, 9.74% of total
Class 9: 1009 samples, 10.09% of total
Total number of clusters (K): 10

## Building the K-Means Algorithm from scratch

We are required to build the K-Means algorithm using three different distance metrices: Euclidean, Cosine Similarity and Generalized Jaccard similarity.

In [16]:
# First we will implement the Euclidean distance function

def euclidean_distance(point1, point2):
    """Calculate the Euclidean distance between two points."""
    return np.sqrt(np.sum((point1 - point2) ** 2))

In [18]:
# Now we will build the K-Means algorithm using Cosine Similarity metric

def cosine_distance(point1, point2):
    """Calculate the Cosine Similarity between two points."""

    # Calculating the dot product between the two points.
    dot_product = np.dot(point1, point2)

    norm1 = np.linalg.norm(point1)
    norm2 = np.linalg.norm(point2)

    # Avoid division by zero
    if norm1 == 0 or norm2 == 0:
        return 1.0
    
    cosine_similarity = dot_product / (norm1 * norm2)

    return 1 - cosine_similarity

In [19]:
# Implementing Generalized Jaccard Similarity

def jaccard_distance(point1, point2):
    """ Calculate the Generalized Jaccard Similarity between two points."""
    numerator = np.sum(np.minimum(point1, point2))
    denominator = np.sum(np.maximum(point1, point2))

    # Avoid division by zero
    if denominator == 0:
        return 1.0
    
    jaccard_similarity = numerator / denominator
    return 1 - jaccard_similarity